version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: ak_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:Z
      - ./postgres/pgdata:/var/lib/postgresql/data/pgdata:Z
      - ./postgres/dumps:/tmp/dumps:Z
      - ./postgres/restore_database.sh:/restore_database.sh:Z
      - ./postgres/restore_ak_dump.sh:/restore_ak_dump.sh:Z
  elasticsearch:
    image: elasticsearch:2.4.6
    container_name: ak_elastic
    ports:
      - 9200:9200
  mail:
    container_name: ak_mail
    image: namshi/smtp
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  ak_core:
    build:
      context: ./
      dockerfile: Dockerfile-core
    volumes:
      - ./airkemist/ak_core:/ak_core:Z
  ak_templates:
    build:
      context: ./
      dockerfile: Dockerfile-templates
    volumes:
      - ./airkemist/ak_templates:/ak_templates:Z
      - ./airkemist/ak_frontend:/ak_templates/lib/ak_frontend:Z
      - ./ak_frontend/css:/ak_templates/lib/ak_frontend/public/css:Z
      - ./ak_frontend/js:/ak_templates/lib/ak_frontend/public/js:Z
      - ./airkemist/ak_templates/package.json:/ak_templates/package.json:Z
      - ./airkemist/ak_templates/package.json:/ak_templates/package-lock.json:Z
      - ./node_modules/ak_templates:/ak_templates/node_modules:Z
  ak_backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    environment:
      - VIRTUAL_HOST=admin.airkemist.local
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    env_file:
      - rails_app_variables.env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./airkemist/ak_backend:/ak_backend:Z
      - ./airkemist/ak_core:/ak_backend/lib/ak_core:Z
      - ./airkemist/ak_templates:/ak_backend/lib/ak_templates:Z
      - ./system:/ak_backend/public/system:Z
      - ./airkemist/ak_backend/package.json:/ak_backend/package.json:Z
      - ./airkemist/ak_backend/package.json:/ak_backend/package-lock.json:Z
      - ./node_modules/ak_backend:/ak_backend/node_modules:Z
    ports:
      - "3000"
    links:
      - postgres
      - elasticsearch
      - mail
    depends_on:
      - postgres
      - elasticsearch
      - mail
      - ak_core
  ak_frontend:
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    environment:
      - VIRTUAL_HOST=~^((www|preview)\.[^a][a-z0-9-]+|[^w][a-z0-9-]+\.airkemist)\.local
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    env_file:
      - rails_app_variables.env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./airkemist/ak_frontend:/ak_frontend:Z
      - ./airkemist/ak_core:/ak_frontend/lib/ak_core:Z
      - ./airkemist/ak_templates:/ak_frontend/lib/ak_templates:Z
      - ./system:/ak_frontend/public/system:Z
      - ./ak_frontend/templates:/ak_frontend/public/templates:Z
      - ./ak_frontend/css:/ak_frontend/public/css:Z
      - ./ak_frontend/js:/ak_frontend/public/js:Z
      - ./airkemist/ak_templates/asset_management/shared:/ak_frontend/public/shared:Z
      - ./airkemist/ak_frontend/package.json:/ak_frontend/package.json:Z
      - ./airkemist/ak_backend/package.json:/ak_backend/package-lock.json:Z
      - ./node_modules/ak_frontend:/ak_frontend/node_modules:Z
    ports:
      - "3000"
    links:
      - postgres
      - elasticsearch
      - mail
    depends_on:
      - postgres
      - elasticsearch
      - mail
      - ak_core
      - ak_templates
  ak_support:
    build:
      context: ./
      dockerfile: Dockerfile-support
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    env_file:
      - rails_app_variables.env
    volumes:
      - ./airkemist/ak_support:/ak_support:Z
      - ./airkemist/ak_core:/ak_support/lib/ak_core:Z
      - ./init-db.sh:/ak_support/init.sh:Z
    links:
      - postgres
      - elasticsearch
    depends_on:
      - postgres
      - elasticsearch
      - ak_core
